# Generated by Django 4.1 on 2024-05-24 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoria',
            table='categoria',
        ),
        migrations.AlterModelTable(
            name='cliente',
            table='cliente',
        ),
        migrations.AlterModelTable(
            name='comuna',
            table='comuna',
        ),
        migrations.AlterModelTable(
            name='historialprecio',
            table='historial_precio',
        ),
        migrations.AlterModelTable(
            name='marca',
            table='marca',
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AlterModelTable(
            name='region',
            table='region',
        ),
        migrations.AlterModelTable(
            name='sucursal',
            table='sucursal',
        ),
        migrations.AlterModelTable(
            name='trabajador',
            table='trabajador',
        ),
    ]
