# Generated by Django 4.1 on 2024-05-25 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0002_alter_categoria_table_alter_cliente_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='comuna',
            name='region',
        ),
        migrations.RemoveField(
            model_name='historialprecio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='sucursal',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='trabajador',
            name='sucursal',
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.comuna'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(db_column='id_region', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.region'),
        ),
        migrations.AddField(
            model_name='historialprecio',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_categoria',
            field=models.ForeignKey(db_column='id_categoria', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.categoria'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_marca',
            field=models.ForeignKey(db_column='id_marca', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.sucursal'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='id_comuna',
            field=models.ForeignKey(db_column='id_comuna', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.comuna'),
        ),
        migrations.AddField(
            model_name='trabajador',
            name='id_sucursal',
            field=models.ForeignKey(db_column='id_sucursal', default=1, on_delete=django.db.models.deletion.CASCADE, to='adm.sucursal'),
        ),
    ]
