# Generated by Django 4.1 on 2024-05-25 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0004_chat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='id_cliente',
            new_name='rut_cliente',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='id_trabajador',
            new_name='rut_trabajador',
        ),
    ]
