# Generated by Django 4.1 on 2024-05-26 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adm', '0005_rename_id_cliente_chat_rut_cliente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='fecha_hora',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='texto_chat',
            new_name='texto',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='rut_cliente',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='rut_trabajador',
        ),
        migrations.AddField(
            model_name='chat',
            name='emisor',
            field=models.CharField(default='erw.gonzalez@duocuc.cl', max_length=255),
        ),
        migrations.AddField(
            model_name='chat',
            name='receptor',
            field=models.CharField(default='erw.gonzalez@duocuc.cl', max_length=255),
        ),
    ]
